### ISSUE TITLE
Realizar el prototipo electrónico y simulación.

### ISSUE THREAD

**Issue by guelo2019** [ISPC-TST-CONTROL-Y-SERVICIOS/proyecto-1-grupo2#7]
Realizar el prototipado del Proyecto,  optamos por la placa de desarrollo ESP32 o ESP8266.
Para el sensor de temperatura  se sugiere el DS18B20, el cual tiene la gran ventaja que ya entrega una señal digital con un ID especifico del sensor, lo que trae como ventaja la identificación del mismo y la zona de sensado.  Además soporta el protocolo 1Wire, lo que implica que con un conductor de 3 hilos (+,- y Data) se puede distribuir la cantidad de sensores que se desee en un solo bus.

Para la simulación se puede utilizar https://wokwi.com/
Se puede cargar código MicroPhyton: https://wokwi.com/projects/new/micropython-esp32
MICROPYTHON ESP32 – Instalación de MicroPython en el microcontrolador ESP32 : https://www.esploradores.com/instalacion_micropython/

**Recursos**:
https://www.maquinasvirtuales.eu/esp32-configurar-wifi-con-micropython/
https://www.solutioon.com/micropython-en-esp32/
https://randomnerdtutorials.com/micropython-ds18b20-esp32-esp8266/
https://randomnerdtutorials.com/micropython-esp32-esp8266-dht11-dht22-web-server/

**Comment by Domi74** [comment]
[https://github.com/ISPC-TST-CONTROL-Y-SERVICIOS/proyecto-1-grupo2.git](url)

**Comment by guelo2019** [comment]
Tarea completa
